[package]
name = "postman-clx"
version = "1.0.0"
edition = "2025"

[[bin]]
name = "postman-clx"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tempfile = "3.8"
which = "4.4"

[build-dependencies]